import "./globals.css";
import type { Metadata } from "next";
import { Nunito } from "next/font/google";
import Navbar from "./components/Navbar";
import Model from "./components/Model";
import Register from "./components/Register";
import ToastProvider from "./providers/ToastProvider";
import GoogleProvider from "./components/GoogleProvider";

const nunito = Nunito({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={nunito.className}>
        <GoogleProvider>
          <ToastProvider />
          <Register />
          <Navbar />
          {children}
        </GoogleProvider>
      </body>
    </html>
  );
}
